const GeoLayout mario_002_switch_opt0_001_switch_opt0_000_switch_headmodel_opt1_switchboneExpression_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(1, mario_switchboneHead_displaylistbone_mesh_mat_override_face_1___Half_Eyes_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_002_switch_opt0_001_switch_opt0_000_switch_headmodel_opt1_switchboneExpression_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(1, mario_switchboneHead_displaylistbone_mesh_mat_override_face_2___Closed_Eyes_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_002_switch_opt0_001_switch_opt0_000_switch_headmodel_opt1_switchboneExpression_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(1, mario_switchboneHead_displaylistbone_mesh_mat_override_face_2___Closed_Eyes_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_002_switch_opt0_001_switch_opt0_000_switch_headmodel_opt1_switchboneExpression_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(1, mario_switchboneHead_displaylistbone_mesh_mat_override_face_2___Closed_Eyes_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_002_switch_opt0_001_switch_opt0_000_switch_headmodel_opt1_switchboneExpression_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(1, mario_switchboneHead_displaylistbone_mesh_mat_override_face_2___Closed_Eyes_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_002_switch_opt0_001_switch_opt0_000_switch_headmodel_opt1_switchboneExpression_opt6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(1, mario_switchboneHead_displaylistbone_mesh_mat_override_face_2___Closed_Eyes_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_002_switch_opt0_001_switch_opt0_000_switch_headmodel_opt1_switchboneExpression_opt7[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(1, mario_switchboneHead_displaylistbone_mesh_mat_override_face_7___Dead_Eyes_4),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_Head_NOCAP_Armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(1, mario_switchboneHead_displaylistbone_mesh),
			GEO_CLOSE_NODE(),
			GEO_BRANCH(1, mario_002_switch_opt0_001_switch_opt0_000_switch_headmodel_opt1_switchboneExpression_opt1),
			GEO_BRANCH(1, mario_002_switch_opt0_001_switch_opt0_000_switch_headmodel_opt1_switchboneExpression_opt2),
			GEO_BRANCH(1, mario_002_switch_opt0_001_switch_opt0_000_switch_headmodel_opt1_switchboneExpression_opt3),
			GEO_BRANCH(1, mario_002_switch_opt0_001_switch_opt0_000_switch_headmodel_opt1_switchboneExpression_opt4),
			GEO_BRANCH(1, mario_002_switch_opt0_001_switch_opt0_000_switch_headmodel_opt1_switchboneExpression_opt5),
			GEO_BRANCH(1, mario_002_switch_opt0_001_switch_opt0_000_switch_headmodel_opt1_switchboneExpression_opt6),
			GEO_BRANCH(1, mario_002_switch_opt0_001_switch_opt0_000_switch_headmodel_opt1_switchboneExpression_opt7),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_LeftHand_OPEN_Armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(1, mario_002_switch_option_LOPEN_000_displaylistOption1_LOPEN_mesh),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_RightHand_OPEN_Armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(1, mario_002_switch_option_LHandOption1_000_displaylist_003__ROPEN_mesh),
		GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_RightHand_PEACE_Armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(1, mario_002_switch_option_RPEACE_000_displaylist_003__RPEACE_mesh),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_RightHand_CAP_Armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(1, mario_002_switch_option_RCAP_000_displaylist_003_RCAP_mesh),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_RightHand_CAP_WING_Armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(4, mario_002_switch_option_RCAPHAND_000_displaylist_003_RCAPHAND_mesh),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_002_switch_opt0_001_switch_opt1_000_switch_headmodel_opt1_switchboneExpression_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(5, mario_switchboneHead_displaylistbone_mesh_mat_override_face_1___Half_Eyes_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_002_switch_opt0_001_switch_opt1_000_switch_headmodel_opt1_switchboneExpression_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(5, mario_switchboneHead_displaylistbone_mesh_mat_override_face_2___Closed_Eyes_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_002_switch_opt0_001_switch_opt1_000_switch_headmodel_opt1_switchboneExpression_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(5, mario_switchboneHead_displaylistbone_mesh_mat_override_face_2___Closed_Eyes_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_002_switch_opt0_001_switch_opt1_000_switch_headmodel_opt1_switchboneExpression_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(5, mario_switchboneHead_displaylistbone_mesh_mat_override_face_2___Closed_Eyes_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_002_switch_opt0_001_switch_opt1_000_switch_headmodel_opt1_switchboneExpression_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(5, mario_switchboneHead_displaylistbone_mesh_mat_override_face_2___Closed_Eyes_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_002_switch_opt0_001_switch_opt1_000_switch_headmodel_opt1_switchboneExpression_opt6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(5, mario_switchboneHead_displaylistbone_mesh_mat_override_face_2___Closed_Eyes_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_002_switch_opt0_001_switch_opt1_000_switch_headmodel_opt1_switchboneExpression_opt7[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(5, mario_switchboneHead_displaylistbone_mesh_mat_override_face_7___Dead_Eyes_4),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_002_switch_opt0_001_switch_opt1_jump_mario_Head_NOCAP_Armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(5, mario_switchboneHead_displaylistbone_mesh),
			GEO_CLOSE_NODE(),
			GEO_BRANCH(1, mario_002_switch_opt0_001_switch_opt1_000_switch_headmodel_opt1_switchboneExpression_opt1),
			GEO_BRANCH(1, mario_002_switch_opt0_001_switch_opt1_000_switch_headmodel_opt1_switchboneExpression_opt2),
			GEO_BRANCH(1, mario_002_switch_opt0_001_switch_opt1_000_switch_headmodel_opt1_switchboneExpression_opt3),
			GEO_BRANCH(1, mario_002_switch_opt0_001_switch_opt1_000_switch_headmodel_opt1_switchboneExpression_opt4),
			GEO_BRANCH(1, mario_002_switch_opt0_001_switch_opt1_000_switch_headmodel_opt1_switchboneExpression_opt5),
			GEO_BRANCH(1, mario_002_switch_opt0_001_switch_opt1_000_switch_headmodel_opt1_switchboneExpression_opt6),
			GEO_BRANCH(1, mario_002_switch_opt0_001_switch_opt1_000_switch_headmodel_opt1_switchboneExpression_opt7),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_002_switch_opt0_001_switch_opt1_jump_mario_LeftHand_OPEN_Armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(5, mario_002_switch_option_LOPEN_000_displaylistOption1_LOPEN_mesh),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_002_switch_opt0_001_switch_opt1_jump_mario_RightHand_OPEN_Armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(5, mario_002_switch_option_LHandOption1_000_displaylist_003__ROPEN_mesh),
		GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_002_switch_opt0_001_switch_opt1_jump_mario_RightHand_PEACE_Armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(5, mario_002_switch_option_RPEACE_000_displaylist_003__RPEACE_mesh),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_002_switch_opt0_001_switch_opt1_jump_mario_RightHand_CAP_Armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(5, mario_002_switch_option_RCAP_000_displaylist_003_RCAP_mesh),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_002_switch_opt0_001_switch_opt1_jump_mario_RightHand_CAP_WING_Armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(5, mario_002_switch_option_RCAPHAND_000_displaylist_003_RCAPHAND_mesh),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_002_switch_opt0_001_switch_opt1_000_switch_headmodel_opt0_000_switch_001_expressions_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(5, mario_000_displaylist_Head_mesh_mat_override_face_1___Half_Eyes_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_002_switch_opt0_001_switch_opt1_000_switch_headmodel_opt0_000_switch_001_expressions_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(5, mario_000_displaylist_Head_mesh_mat_override_face_2___Closed_Eyes_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_002_switch_opt0_001_switch_opt1_000_switch_headmodel_opt0_000_switch_001_expressions_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(5, mario_000_displaylist_Head_mesh_mat_override_face_2___Closed_Eyes_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_002_switch_opt0_001_switch_opt1_000_switch_headmodel_opt0_000_switch_001_expressions_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(5, mario_000_displaylist_Head_mesh_mat_override_face_2___Closed_Eyes_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_002_switch_opt0_001_switch_opt1_000_switch_headmodel_opt0_000_switch_001_expressions_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(5, mario_000_displaylist_Head_mesh_mat_override_face_2___Closed_Eyes_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_002_switch_opt0_001_switch_opt1_000_switch_headmodel_opt0_000_switch_001_expressions_opt6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(5, mario_000_displaylist_Head_mesh_mat_override_face_2___Closed_Eyes_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_002_switch_opt0_001_switch_opt1_000_switch_headmodel_opt0_000_switch_001_expressions_opt7[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(5, mario_000_displaylist_Head_mesh_mat_override_face_7___Dead_Eyes_4),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_002_switch_opt0_001_switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(5, 0, 0, 0, mario_000_offset_bottom_mesh),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(5, mario_000_offset_001_Chest_skinned),
				GEO_ASM(0, geo_move_mario_part_from_parent),
				GEO_ASM(0, geo_mario_tilt_torso),
				GEO_ROTATION_NODE(0, 0, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(5, 68, 0, 0, mario_000_offset_001_Chest_mesh),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(1, 87, 0, 0, NULL),
						GEO_OPEN_NODE(),
							GEO_ASM(0, geo_mario_head_rotation),
							GEO_ROTATION_NODE(0, 0, 0, 0),
							GEO_OPEN_NODE(),
								GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
								GEO_OPEN_NODE(),
									GEO_NODE_START(),
									GEO_OPEN_NODE(),
										GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(5, mario_000_displaylist_Head_mesh),
											GEO_CLOSE_NODE(),
											GEO_BRANCH(1, mario_002_switch_opt0_001_switch_opt1_000_switch_headmodel_opt0_000_switch_001_expressions_opt1),
											GEO_BRANCH(1, mario_002_switch_opt0_001_switch_opt1_000_switch_headmodel_opt0_000_switch_001_expressions_opt2),
											GEO_BRANCH(1, mario_002_switch_opt0_001_switch_opt1_000_switch_headmodel_opt0_000_switch_001_expressions_opt3),
											GEO_BRANCH(1, mario_002_switch_opt0_001_switch_opt1_000_switch_headmodel_opt0_000_switch_001_expressions_opt4),
											GEO_BRANCH(1, mario_002_switch_opt0_001_switch_opt1_000_switch_headmodel_opt0_000_switch_001_expressions_opt5),
											GEO_BRANCH(1, mario_002_switch_opt0_001_switch_opt1_000_switch_headmodel_opt0_000_switch_001_expressions_opt6),
											GEO_BRANCH(1, mario_002_switch_opt0_001_switch_opt1_000_switch_headmodel_opt0_000_switch_001_expressions_opt7),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
									GEO_BRANCH(1, mario_002_switch_opt0_001_switch_opt1_jump_mario_Head_NOCAP_Armature),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(0, 142, -51, -126, 15, -33, -133),
								GEO_OPEN_NODE(),
									GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
									GEO_ROTATION_NODE(0, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(5, mario_000_displaylist_001_RWing_mesh),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(0, 142, -51, 126, -15, 33, -133),
								GEO_OPEN_NODE(),
									GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
									GEO_ROTATION_NODE(0, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(5, mario_000_displaylist_002_LWing_mesh),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_DISPLAY_LIST(5, mario_000_offset_003_LShoulder_skinned),
						GEO_ANIMATED_PART(1, 67, -10, 79, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(5, 0, 0, 0, mario_000_offset_003_LShoulder_mesh),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(5, mario_000_offset_004_LArm_skinned),
								GEO_ANIMATED_PART(5, 65, 0, 0, mario_000_offset_004_LArm_mesh),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(5, mario_000_offset_005_LHand_skinned),
									GEO_ASM(1, geo_mario_hand_foot_scaler),
									GEO_SCALE(0, 65536),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(5, 60, 0, 0, mario_000_offset_005_LHand_mesh),
										GEO_OPEN_NODE(),
											GEO_SWITCH_CASE(1, geo_switch_mario_hand),
											GEO_OPEN_NODE(),
												GEO_NODE_START(),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(5, mario_000_displaylist_003_LHand_mesh),
												GEO_CLOSE_NODE(),
												GEO_BRANCH(1, mario_002_switch_opt0_001_switch_opt1_jump_mario_LeftHand_OPEN_Armature),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_DISPLAY_LIST(5, mario_000_offset_006_Rshoulder_skinned),
						GEO_ANIMATED_PART(1, 68, -10, -79, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(5, 0, 0, 0, mario_000_offset_006_Rshoulder_mesh),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(5, mario_000_offset_007_RArm_skinned),
								GEO_ANIMATED_PART(5, 65, 0, 0, mario_000_offset_007_RArm_mesh),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(5, mario_000_offset_008_RHand_skinned),
									GEO_ASM(0, geo_mario_hand_foot_scaler),
									GEO_SCALE(0, 65536),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(5, 60, 0, 0, mario_000_offset_008_RHand_mesh),
										GEO_OPEN_NODE(),
											GEO_SWITCH_CASE(0, geo_switch_mario_hand),
											GEO_OPEN_NODE(),
												GEO_NODE_START(),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(5, mario_000_displaylist_004_Rhand_mesh),
													GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
												GEO_CLOSE_NODE(),
												GEO_BRANCH(1, mario_002_switch_opt0_001_switch_opt1_jump_mario_RightHand_OPEN_Armature),
												GEO_BRANCH(1, mario_002_switch_opt0_001_switch_opt1_jump_mario_RightHand_PEACE_Armature),
												GEO_BRANCH(1, mario_002_switch_opt0_001_switch_opt1_jump_mario_RightHand_CAP_Armature),
												GEO_BRANCH(1, mario_002_switch_opt0_001_switch_opt1_jump_mario_RightHand_CAP_WING_Armature),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_DISPLAY_LIST(5, mario_000_offset_009_LThigh_skinned),
				GEO_ANIMATED_PART(1, 13, -8, 42, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(5, 0, 0, 0, mario_000_offset_009_LThigh_mesh),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(5, mario_000_offset_010_LLeg_skinned),
						GEO_ANIMATED_PART(5, 89, 0, 0, mario_000_offset_010_LLeg_mesh),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(5, mario_000_offset_011_LFoot_skinned),
							GEO_ANIMATED_PART(5, 67, 0, 0, mario_000_offset_011_LFoot_mesh),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_DISPLAY_LIST(5, mario_000_offset_012_RThigh_skinned),
				GEO_ANIMATED_PART(1, 13, -8, -42, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(5, 0, 0, 0, mario_000_offset_012_RThigh_mesh),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(5, mario_000_offset_013_RLeg_skinned),
						GEO_ANIMATED_PART(5, 89, 0, 0, mario_000_offset_013_RLeg_mesh),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(5, mario_000_displaylist_005_RFoot_skinned),
							GEO_ANIMATED_PART(1, 67, 0, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_ASM(2, geo_mario_hand_foot_scaler),
								GEO_SCALE(0, 65536),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(5, mario_000_displaylist_005_RFoot_mesh),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_002_switch_opt0_001_switch_opt2_jump_mario_Head_NOCAP_Armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(1, mario_switchboneHead_displaylistbone_mesh_mat_override_metal_0),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_002_switch_opt0_001_switch_opt2_jump_mario_LeftHand_OPEN_Armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(1, mario_002_switch_option_LOPEN_000_displaylistOption1_LOPEN_mesh_mat_override_metal_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_002_switch_opt0_001_switch_opt2_jump_mario_RightHand_OPEN_Armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(1, mario_002_switch_option_LHandOption1_000_displaylist_003__ROPEN_mesh_mat_override_metal_0),
		GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_002_switch_opt0_001_switch_opt2_jump_mario_RightHand_PEACE_Armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(1, mario_002_switch_option_RPEACE_000_displaylist_003__RPEACE_mesh_mat_override_metal_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_002_switch_opt0_001_switch_opt2_jump_mario_RightHand_CAP_Armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(1, mario_002_switch_option_RCAP_000_displaylist_003_RCAP_mesh_mat_override_metal_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_002_switch_opt0_001_switch_opt2_jump_mario_RightHand_CAP_WING_Armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(4, mario_002_switch_option_RCAPHAND_000_displaylist_003_RCAPHAND_mesh_mat_override_metal_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_002_switch_opt0_001_switch_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(1, 0, 0, 0, mario_000_offset_bottom_mesh_mat_override_metal_0),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(1, mario_000_offset_001_Chest_skinned_mat_override_metal_0),
				GEO_ASM(0, geo_move_mario_part_from_parent),
				GEO_ASM(0, geo_mario_tilt_torso),
				GEO_ROTATION_NODE(0, 0, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(1, 68, 0, 0, mario_000_offset_001_Chest_mesh_mat_override_metal_0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(1, 87, 0, 0, NULL),
						GEO_OPEN_NODE(),
							GEO_ASM(0, geo_mario_head_rotation),
							GEO_ROTATION_NODE(0, 0, 0, 0),
							GEO_OPEN_NODE(),
								GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
								GEO_OPEN_NODE(),
									GEO_NODE_START(),
									GEO_OPEN_NODE(),
										GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(1, mario_000_displaylist_Head_mesh_mat_override_metal_0),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
									GEO_BRANCH(1, mario_002_switch_opt0_001_switch_opt2_jump_mario_Head_NOCAP_Armature),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(0, 142, -51, -126, 15, -33, -133),
								GEO_OPEN_NODE(),
									GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
									GEO_ROTATION_NODE(0, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(4, mario_000_displaylist_001_RWing_mesh_mat_override_metal_0),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(0, 142, -51, 126, -15, 33, -133),
								GEO_OPEN_NODE(),
									GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
									GEO_ROTATION_NODE(0, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(4, mario_000_displaylist_002_LWing_mesh_mat_override_metal_0),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_DISPLAY_LIST(1, mario_000_offset_003_LShoulder_skinned_mat_override_metal_0),
						GEO_ANIMATED_PART(1, 67, -10, 79, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(1, 0, 0, 0, mario_000_offset_003_LShoulder_mesh_mat_override_metal_0),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(1, mario_000_offset_004_LArm_skinned_mat_override_metal_0),
								GEO_ANIMATED_PART(1, 65, 0, 0, mario_000_offset_004_LArm_mesh_mat_override_metal_0),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(1, mario_000_offset_005_LHand_skinned_mat_override_metal_0),
									GEO_ASM(1, geo_mario_hand_foot_scaler),
									GEO_SCALE(0, 65536),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(1, 60, 0, 0, mario_000_offset_005_LHand_mesh_mat_override_metal_0),
										GEO_OPEN_NODE(),
											GEO_SWITCH_CASE(1, geo_switch_mario_hand),
											GEO_OPEN_NODE(),
												GEO_NODE_START(),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(1, mario_000_displaylist_003_LHand_mesh_mat_override_metal_0),
												GEO_CLOSE_NODE(),
												GEO_BRANCH(1, mario_002_switch_opt0_001_switch_opt2_jump_mario_LeftHand_OPEN_Armature),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_DISPLAY_LIST(1, mario_000_offset_006_Rshoulder_skinned_mat_override_metal_0),
						GEO_ANIMATED_PART(1, 68, -10, -79, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(1, 0, 0, 0, mario_000_offset_006_Rshoulder_mesh_mat_override_metal_0),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(1, mario_000_offset_007_RArm_skinned_mat_override_metal_0),
								GEO_ANIMATED_PART(1, 65, 0, 0, mario_000_offset_007_RArm_mesh_mat_override_metal_0),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(1, mario_000_offset_008_RHand_skinned_mat_override_metal_0),
									GEO_ASM(0, geo_mario_hand_foot_scaler),
									GEO_SCALE(0, 65536),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(1, 60, 0, 0, mario_000_offset_008_RHand_mesh_mat_override_metal_0),
										GEO_OPEN_NODE(),
											GEO_SWITCH_CASE(0, geo_switch_mario_hand),
											GEO_OPEN_NODE(),
												GEO_NODE_START(),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(1, mario_000_displaylist_004_Rhand_mesh_mat_override_metal_0),
													GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
												GEO_CLOSE_NODE(),
												GEO_BRANCH(1, mario_002_switch_opt0_001_switch_opt2_jump_mario_RightHand_OPEN_Armature),
												GEO_BRANCH(1, mario_002_switch_opt0_001_switch_opt2_jump_mario_RightHand_PEACE_Armature),
												GEO_BRANCH(1, mario_002_switch_opt0_001_switch_opt2_jump_mario_RightHand_CAP_Armature),
												GEO_BRANCH(1, mario_002_switch_opt0_001_switch_opt2_jump_mario_RightHand_CAP_WING_Armature),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_DISPLAY_LIST(1, mario_000_offset_009_LThigh_skinned_mat_override_metal_0),
				GEO_ANIMATED_PART(1, 13, -8, 42, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(1, 0, 0, 0, mario_000_offset_009_LThigh_mesh_mat_override_metal_0),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(1, mario_000_offset_010_LLeg_skinned_mat_override_metal_0),
						GEO_ANIMATED_PART(1, 89, 0, 0, mario_000_offset_010_LLeg_mesh_mat_override_metal_0),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(1, mario_000_offset_011_LFoot_skinned_mat_override_metal_0),
							GEO_ANIMATED_PART(1, 67, 0, 0, mario_000_offset_011_LFoot_mesh_mat_override_metal_0),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_DISPLAY_LIST(1, mario_000_offset_012_RThigh_skinned_mat_override_metal_0),
				GEO_ANIMATED_PART(1, 13, -8, -42, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(1, 0, 0, 0, mario_000_offset_012_RThigh_mesh_mat_override_metal_0),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(1, mario_000_offset_013_RLeg_skinned_mat_override_metal_0),
						GEO_ANIMATED_PART(1, 89, 0, 0, mario_000_offset_013_RLeg_mesh_mat_override_metal_0),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(1, mario_000_displaylist_005_RFoot_skinned_mat_override_metal_0),
							GEO_ANIMATED_PART(1, 67, 0, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_ASM(2, geo_mario_hand_foot_scaler),
								GEO_SCALE(0, 65536),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(1, mario_000_displaylist_005_RFoot_mesh_mat_override_metal_0),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_002_switch_opt0_001_switch_opt3_jump_mario_Head_NOCAP_Armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(5, mario_switchboneHead_displaylistbone_mesh_mat_override_metal_0),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_002_switch_opt0_001_switch_opt3_jump_mario_LeftHand_OPEN_Armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(5, mario_002_switch_option_LOPEN_000_displaylistOption1_LOPEN_mesh_mat_override_metal_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_002_switch_opt0_001_switch_opt3_jump_mario_RightHand_OPEN_Armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(5, mario_002_switch_option_LHandOption1_000_displaylist_003__ROPEN_mesh_mat_override_metal_0),
		GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_002_switch_opt0_001_switch_opt3_jump_mario_RightHand_PEACE_Armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(5, mario_002_switch_option_RPEACE_000_displaylist_003__RPEACE_mesh_mat_override_metal_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_002_switch_opt0_001_switch_opt3_jump_mario_RightHand_CAP_Armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(5, mario_002_switch_option_RCAP_000_displaylist_003_RCAP_mesh_mat_override_metal_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_002_switch_opt0_001_switch_opt3_jump_mario_RightHand_CAP_WING_Armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(5, mario_002_switch_option_RCAPHAND_000_displaylist_003_RCAPHAND_mesh_mat_override_metal_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_002_switch_opt0_001_switch_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(5, 0, 0, 0, mario_000_offset_bottom_mesh_mat_override_metal_0),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(5, mario_000_offset_001_Chest_skinned_mat_override_metal_0),
				GEO_ASM(0, geo_move_mario_part_from_parent),
				GEO_ASM(0, geo_mario_tilt_torso),
				GEO_ROTATION_NODE(0, 0, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(5, 68, 0, 0, mario_000_offset_001_Chest_mesh_mat_override_metal_0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(1, 87, 0, 0, NULL),
						GEO_OPEN_NODE(),
							GEO_ASM(0, geo_mario_head_rotation),
							GEO_ROTATION_NODE(0, 0, 0, 0),
							GEO_OPEN_NODE(),
								GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
								GEO_OPEN_NODE(),
									GEO_NODE_START(),
									GEO_OPEN_NODE(),
										GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(5, mario_000_displaylist_Head_mesh_mat_override_metal_0),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
									GEO_BRANCH(1, mario_002_switch_opt0_001_switch_opt3_jump_mario_Head_NOCAP_Armature),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(0, 142, -51, -126, 15, -33, -133),
								GEO_OPEN_NODE(),
									GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
									GEO_ROTATION_NODE(0, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(5, mario_000_displaylist_001_RWing_mesh_mat_override_metal_0),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(0, 142, -51, 126, -15, 33, -133),
								GEO_OPEN_NODE(),
									GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
									GEO_ROTATION_NODE(0, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(5, mario_000_displaylist_002_LWing_mesh_mat_override_metal_0),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_DISPLAY_LIST(5, mario_000_offset_003_LShoulder_skinned_mat_override_metal_0),
						GEO_ANIMATED_PART(1, 67, -10, 79, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(5, 0, 0, 0, mario_000_offset_003_LShoulder_mesh_mat_override_metal_0),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(5, mario_000_offset_004_LArm_skinned_mat_override_metal_0),
								GEO_ANIMATED_PART(5, 65, 0, 0, mario_000_offset_004_LArm_mesh_mat_override_metal_0),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(5, mario_000_offset_005_LHand_skinned_mat_override_metal_0),
									GEO_ASM(1, geo_mario_hand_foot_scaler),
									GEO_SCALE(0, 65536),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(5, 60, 0, 0, mario_000_offset_005_LHand_mesh_mat_override_metal_0),
										GEO_OPEN_NODE(),
											GEO_SWITCH_CASE(1, geo_switch_mario_hand),
											GEO_OPEN_NODE(),
												GEO_NODE_START(),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(5, mario_000_displaylist_003_LHand_mesh_mat_override_metal_0),
												GEO_CLOSE_NODE(),
												GEO_BRANCH(1, mario_002_switch_opt0_001_switch_opt3_jump_mario_LeftHand_OPEN_Armature),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_DISPLAY_LIST(5, mario_000_offset_006_Rshoulder_skinned_mat_override_metal_0),
						GEO_ANIMATED_PART(1, 68, -10, -79, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(5, 0, 0, 0, mario_000_offset_006_Rshoulder_mesh_mat_override_metal_0),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(5, mario_000_offset_007_RArm_skinned_mat_override_metal_0),
								GEO_ANIMATED_PART(5, 65, 0, 0, mario_000_offset_007_RArm_mesh_mat_override_metal_0),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(5, mario_000_offset_008_RHand_skinned_mat_override_metal_0),
									GEO_ASM(0, geo_mario_hand_foot_scaler),
									GEO_SCALE(0, 65536),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(5, 60, 0, 0, mario_000_offset_008_RHand_mesh_mat_override_metal_0),
										GEO_OPEN_NODE(),
											GEO_SWITCH_CASE(0, geo_switch_mario_hand),
											GEO_OPEN_NODE(),
												GEO_NODE_START(),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(5, mario_000_displaylist_004_Rhand_mesh_mat_override_metal_0),
													GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
												GEO_CLOSE_NODE(),
												GEO_BRANCH(1, mario_002_switch_opt0_001_switch_opt3_jump_mario_RightHand_OPEN_Armature),
												GEO_BRANCH(1, mario_002_switch_opt0_001_switch_opt3_jump_mario_RightHand_PEACE_Armature),
												GEO_BRANCH(1, mario_002_switch_opt0_001_switch_opt3_jump_mario_RightHand_CAP_Armature),
												GEO_BRANCH(1, mario_002_switch_opt0_001_switch_opt3_jump_mario_RightHand_CAP_WING_Armature),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_DISPLAY_LIST(5, mario_000_offset_009_LThigh_skinned_mat_override_metal_0),
				GEO_ANIMATED_PART(1, 13, -8, 42, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(5, 0, 0, 0, mario_000_offset_009_LThigh_mesh_mat_override_metal_0),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(5, mario_000_offset_010_LLeg_skinned_mat_override_metal_0),
						GEO_ANIMATED_PART(5, 89, 0, 0, mario_000_offset_010_LLeg_mesh_mat_override_metal_0),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(5, mario_000_offset_011_LFoot_skinned_mat_override_metal_0),
							GEO_ANIMATED_PART(5, 67, 0, 0, mario_000_offset_011_LFoot_mesh_mat_override_metal_0),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_DISPLAY_LIST(5, mario_000_offset_012_RThigh_skinned_mat_override_metal_0),
				GEO_ANIMATED_PART(1, 13, -8, -42, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(5, 0, 0, 0, mario_000_offset_012_RThigh_mesh_mat_override_metal_0),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(5, mario_000_offset_013_RLeg_skinned_mat_override_metal_0),
						GEO_ANIMATED_PART(5, 89, 0, 0, mario_000_offset_013_RLeg_mesh_mat_override_metal_0),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(5, mario_000_displaylist_005_RFoot_skinned_mat_override_metal_0),
							GEO_ANIMATED_PART(1, 67, 0, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_ASM(2, geo_mario_hand_foot_scaler),
								GEO_SCALE(0, 65536),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(5, mario_000_displaylist_005_RFoot_mesh_mat_override_metal_0),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_002_switch_opt0_001_switch_opt0_000_switch_headmodel_opt0_000_switch_001_expressions_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(1, mario_000_displaylist_Head_mesh_mat_override_face_1___Half_Eyes_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_002_switch_opt0_001_switch_opt0_000_switch_headmodel_opt0_000_switch_001_expressions_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(1, mario_000_displaylist_Head_mesh_mat_override_face_2___Closed_Eyes_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_002_switch_opt0_001_switch_opt0_000_switch_headmodel_opt0_000_switch_001_expressions_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(1, mario_000_displaylist_Head_mesh_mat_override_face_2___Closed_Eyes_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_002_switch_opt0_001_switch_opt0_000_switch_headmodel_opt0_000_switch_001_expressions_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(1, mario_000_displaylist_Head_mesh_mat_override_face_2___Closed_Eyes_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_002_switch_opt0_001_switch_opt0_000_switch_headmodel_opt0_000_switch_001_expressions_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(1, mario_000_displaylist_Head_mesh_mat_override_face_2___Closed_Eyes_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_002_switch_opt0_001_switch_opt0_000_switch_headmodel_opt0_000_switch_001_expressions_opt6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(1, mario_000_displaylist_Head_mesh_mat_override_face_2___Closed_Eyes_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_002_switch_opt0_001_switch_opt0_000_switch_headmodel_opt0_000_switch_001_expressions_opt7[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(1, mario_000_displaylist_Head_mesh_mat_override_face_7___Dead_Eyes_4),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SHADOW(1, 180, 100),
		GEO_OPEN_NODE(),
			GEO_SCALE(0, 16384),
			GEO_OPEN_NODE(),
				GEO_ASM(0, geo_mirror_mario_backface_culling),
				GEO_ASM(0, geo_mirror_mario_set_alpha),
				GEO_SWITCH_CASE(0, geo_switch_mario_stand_run),
				GEO_OPEN_NODE(),
					GEO_NODE_START(),
					GEO_OPEN_NODE(),
						GEO_SWITCH_CASE(0, geo_switch_mario_cap_effect),
						GEO_OPEN_NODE(),
							GEO_NODE_START(),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(1, 0, 0, 0, mario_000_offset_bottom_mesh),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(1, mario_000_offset_001_Chest_skinned),
										GEO_ASM(0, geo_move_mario_part_from_parent),
										GEO_ASM(0, geo_mario_tilt_torso),
										GEO_ROTATION_NODE(0, 0, 0, 0),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(1, 68, 0, 0, mario_000_offset_001_Chest_mesh),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(1, 87, 0, 0, NULL),
												GEO_OPEN_NODE(),
													GEO_ASM(0, geo_mario_head_rotation),
													GEO_ROTATION_NODE(0, 0, 0, 0),
													GEO_OPEN_NODE(),
														GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
														GEO_OPEN_NODE(),
															GEO_NODE_START(),
															GEO_OPEN_NODE(),
																GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
																GEO_OPEN_NODE(),
																	GEO_NODE_START(),
																	GEO_OPEN_NODE(),
																		GEO_DISPLAY_LIST(1, mario_000_displaylist_Head_mesh),
																	GEO_CLOSE_NODE(),
																	GEO_BRANCH(1, mario_002_switch_opt0_001_switch_opt0_000_switch_headmodel_opt0_000_switch_001_expressions_opt1),
																	GEO_BRANCH(1, mario_002_switch_opt0_001_switch_opt0_000_switch_headmodel_opt0_000_switch_001_expressions_opt2),
																	GEO_BRANCH(1, mario_002_switch_opt0_001_switch_opt0_000_switch_headmodel_opt0_000_switch_001_expressions_opt3),
																	GEO_BRANCH(1, mario_002_switch_opt0_001_switch_opt0_000_switch_headmodel_opt0_000_switch_001_expressions_opt4),
																	GEO_BRANCH(1, mario_002_switch_opt0_001_switch_opt0_000_switch_headmodel_opt0_000_switch_001_expressions_opt5),
																	GEO_BRANCH(1, mario_002_switch_opt0_001_switch_opt0_000_switch_headmodel_opt0_000_switch_001_expressions_opt6),
																	GEO_BRANCH(1, mario_002_switch_opt0_001_switch_opt0_000_switch_headmodel_opt0_000_switch_001_expressions_opt7),
																GEO_CLOSE_NODE(),
															GEO_CLOSE_NODE(),
															GEO_BRANCH(1, mario_Head_NOCAP_Armature),
														GEO_CLOSE_NODE(),
														GEO_TRANSLATE_ROTATE(0, 142, -51, -126, 15, -33, -133),
														GEO_OPEN_NODE(),
															GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
															GEO_ROTATION_NODE(0, 0, 0, 0),
															GEO_OPEN_NODE(),
																GEO_DISPLAY_LIST(4, mario_000_displaylist_001_RWing_mesh),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
														GEO_TRANSLATE_ROTATE(0, 142, -51, 126, -15, 33, -133),
														GEO_OPEN_NODE(),
															GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
															GEO_ROTATION_NODE(0, 0, 0, 0),
															GEO_OPEN_NODE(),
																GEO_DISPLAY_LIST(4, mario_000_displaylist_002_LWing_mesh),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
												GEO_DISPLAY_LIST(1, mario_000_offset_003_LShoulder_skinned),
												GEO_ANIMATED_PART(1, 67, -10, 79, NULL),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(1, 0, 0, 0, mario_000_offset_003_LShoulder_mesh),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(1, mario_000_offset_004_LArm_skinned),
														GEO_ANIMATED_PART(1, 65, 0, 0, mario_000_offset_004_LArm_mesh),
														GEO_OPEN_NODE(),
															GEO_DISPLAY_LIST(1, mario_000_offset_005_LHand_skinned),
															GEO_ASM(1, geo_mario_hand_foot_scaler),
															GEO_SCALE(0, 65536),
															GEO_OPEN_NODE(),
																GEO_ANIMATED_PART(1, 60, 0, 0, mario_000_offset_005_LHand_mesh),
																GEO_OPEN_NODE(),
																	GEO_SWITCH_CASE(1, geo_switch_mario_hand),
																	GEO_OPEN_NODE(),
																		GEO_NODE_START(),
																		GEO_OPEN_NODE(),
																			GEO_DISPLAY_LIST(1, mario_000_displaylist_003_LHand_mesh),
																		GEO_CLOSE_NODE(),
																		GEO_BRANCH(1, mario_LeftHand_OPEN_Armature),
																	GEO_CLOSE_NODE(),
																GEO_CLOSE_NODE(),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
												GEO_DISPLAY_LIST(1, mario_000_offset_006_Rshoulder_skinned),
												GEO_ANIMATED_PART(1, 68, -10, -79, NULL),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(1, 0, 0, 0, mario_000_offset_006_Rshoulder_mesh),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(1, mario_000_offset_007_RArm_skinned),
														GEO_ANIMATED_PART(1, 65, 0, 0, mario_000_offset_007_RArm_mesh),
														GEO_OPEN_NODE(),
															GEO_DISPLAY_LIST(1, mario_000_offset_008_RHand_skinned),
															GEO_ASM(0, geo_mario_hand_foot_scaler),
															GEO_SCALE(0, 65536),
															GEO_OPEN_NODE(),
																GEO_ANIMATED_PART(1, 60, 0, 0, mario_000_offset_008_RHand_mesh),
																GEO_OPEN_NODE(),
																	GEO_SWITCH_CASE(0, geo_switch_mario_hand),
																	GEO_OPEN_NODE(),
																		GEO_NODE_START(),
																		GEO_OPEN_NODE(),
																			GEO_DISPLAY_LIST(1, mario_000_displaylist_004_Rhand_mesh),
																			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
																		GEO_CLOSE_NODE(),
																		GEO_BRANCH(1, mario_RightHand_OPEN_Armature),
																		GEO_BRANCH(1, mario_RightHand_PEACE_Armature),
																		GEO_BRANCH(1, mario_RightHand_CAP_Armature),
																		GEO_BRANCH(1, mario_RightHand_CAP_WING_Armature),
																	GEO_CLOSE_NODE(),
																GEO_CLOSE_NODE(),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_DISPLAY_LIST(1, mario_000_offset_009_LThigh_skinned),
										GEO_ANIMATED_PART(1, 13, -8, 42, NULL),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(1, 0, 0, 0, mario_000_offset_009_LThigh_mesh),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(1, mario_000_offset_010_LLeg_skinned),
												GEO_ANIMATED_PART(1, 89, 0, 0, mario_000_offset_010_LLeg_mesh),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(1, mario_000_offset_011_LFoot_skinned),
													GEO_ANIMATED_PART(1, 67, 0, 0, mario_000_offset_011_LFoot_mesh),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_DISPLAY_LIST(1, mario_000_offset_012_RThigh_skinned),
										GEO_ANIMATED_PART(1, 13, -8, -42, NULL),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(1, 0, 0, 0, mario_000_offset_012_RThigh_mesh),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(1, mario_000_offset_013_RLeg_skinned),
												GEO_ANIMATED_PART(1, 89, 0, 0, mario_000_offset_013_RLeg_mesh),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(1, mario_000_displaylist_005_RFoot_skinned),
													GEO_ANIMATED_PART(1, 67, 0, 0, NULL),
													GEO_OPEN_NODE(),
														GEO_ASM(2, geo_mario_hand_foot_scaler),
														GEO_SCALE(0, 65536),
														GEO_OPEN_NODE(),
															GEO_DISPLAY_LIST(1, mario_000_displaylist_005_RFoot_mesh),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_BRANCH(1, mario_002_switch_opt0_001_switch_opt1),
							GEO_BRANCH(1, mario_002_switch_opt0_001_switch_opt2),
							GEO_BRANCH(1, mario_002_switch_opt0_001_switch_opt3),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ASM(1, geo_mirror_mario_backface_culling),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(0, mario_material_revert_render_settings),
		GEO_DISPLAY_LIST(1, mario_material_revert_render_settings),
		GEO_DISPLAY_LIST(2, mario_material_revert_render_settings),
		GEO_DISPLAY_LIST(3, mario_material_revert_render_settings),
		GEO_DISPLAY_LIST(4, mario_material_revert_render_settings),
		GEO_DISPLAY_LIST(5, mario_material_revert_render_settings),
		GEO_DISPLAY_LIST(6, mario_material_revert_render_settings),
		GEO_DISPLAY_LIST(7, mario_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
