const GeoLayout imbie_002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(1, imbie_002_switch_option_head__no_cap__mesh_mat_override_face_1___eye_half_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout imbie_002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(1, imbie_002_switch_option_head__no_cap__mesh_mat_override_face_2___eye_closed_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout imbie_002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(1, imbie_002_switch_option_head__no_cap__mesh_mat_override_face_2___eye_closed_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout imbie_002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(1, imbie_002_switch_option_head__no_cap__mesh_mat_override_face_2___eye_closed_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout imbie_002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(1, imbie_002_switch_option_head__no_cap__mesh_mat_override_face_2___eye_closed_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout imbie_002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(1, imbie_002_switch_option_head__no_cap__mesh_mat_override_face_2___eye_closed_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout imbie_002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt7[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(1, imbie_002_switch_option_head__no_cap__mesh_mat_override_face_7___eye_X_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout imbie_armature_002_switch_option_002[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(1, imbie_002_switch_option_head__no_cap__mesh),
			GEO_CLOSE_NODE(),
			GEO_BRANCH(1, imbie_002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt1),
			GEO_BRANCH(1, imbie_002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt2),
			GEO_BRANCH(1, imbie_002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt3),
			GEO_BRANCH(1, imbie_002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt4),
			GEO_BRANCH(1, imbie_002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt5),
			GEO_BRANCH(1, imbie_002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt6),
			GEO_BRANCH(1, imbie_002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt7),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout imbie_right_hand_open_armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(1, 60, 0, 0, imbie_002_switch_option_right_hand_open_mesh),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout imbie_left_hand_open_armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(1, 60, 0, 0, imbie_002_switch_option_left_hand_open_mesh),
		GEO_OPEN_NODE(),
			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout imbie_left_hand_peace_armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(1, 60, 0, 0, imbie_004_switch_option_left_hand_peace_mesh),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout imbie_left_hand_cap_armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(1, 60, 0, 0, imbie_005_switch_option_left_hand_cap_mesh),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout imbie_left_hand_wing_cap_armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(1, 60, 0, 0, imbie_006_switch_option_left_hand_wing_cap_mesh),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(4, imbie_006_switch_option_left_hand_wing_cap_wings_mesh),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout imbie_002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(5, imbie_002_switch_option_head__no_cap__mesh_mat_override_face_1___eye_half_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout imbie_002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(5, imbie_002_switch_option_head__no_cap__mesh_mat_override_face_2___eye_closed_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout imbie_002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(5, imbie_002_switch_option_head__no_cap__mesh_mat_override_face_2___eye_closed_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout imbie_002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(5, imbie_002_switch_option_head__no_cap__mesh_mat_override_face_2___eye_closed_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout imbie_002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(5, imbie_002_switch_option_head__no_cap__mesh_mat_override_face_2___eye_closed_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout imbie_002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(5, imbie_002_switch_option_head__no_cap__mesh_mat_override_face_2___eye_closed_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout imbie_002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt7[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(5, imbie_002_switch_option_head__no_cap__mesh_mat_override_face_7___eye_X_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout imbie_002_switch_opt0_001_switch_opt1_jump_imbie_armature_002_switch_option_002[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(5, imbie_002_switch_option_head__no_cap__mesh),
			GEO_CLOSE_NODE(),
			GEO_BRANCH(1, imbie_002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt1),
			GEO_BRANCH(1, imbie_002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt2),
			GEO_BRANCH(1, imbie_002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt3),
			GEO_BRANCH(1, imbie_002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt4),
			GEO_BRANCH(1, imbie_002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt5),
			GEO_BRANCH(1, imbie_002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt6),
			GEO_BRANCH(1, imbie_002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt7),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout imbie_002_switch_opt0_001_switch_opt1_jump_imbie_right_hand_open_armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(5, 60, 0, 0, imbie_002_switch_option_right_hand_open_mesh),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout imbie_002_switch_opt0_001_switch_opt1_jump_imbie_left_hand_open_armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(5, 60, 0, 0, imbie_002_switch_option_left_hand_open_mesh),
		GEO_OPEN_NODE(),
			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout imbie_002_switch_opt0_001_switch_opt1_jump_imbie_left_hand_peace_armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(5, 60, 0, 0, imbie_004_switch_option_left_hand_peace_mesh),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout imbie_002_switch_opt0_001_switch_opt1_jump_imbie_left_hand_cap_armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(5, 60, 0, 0, imbie_005_switch_option_left_hand_cap_mesh),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout imbie_002_switch_opt0_001_switch_opt1_jump_imbie_left_hand_wing_cap_armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(5, 60, 0, 0, imbie_006_switch_option_left_hand_wing_cap_mesh),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(5, imbie_006_switch_option_left_hand_wing_cap_wings_mesh),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout imbie_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(5, imbie_000_displaylist_mesh_mat_override_face_1___eye_half_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout imbie_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(5, imbie_000_displaylist_mesh_mat_override_face_2___eye_closed_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout imbie_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(5, imbie_000_displaylist_mesh_mat_override_face_2___eye_closed_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout imbie_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(5, imbie_000_displaylist_mesh_mat_override_face_2___eye_closed_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout imbie_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(5, imbie_000_displaylist_mesh_mat_override_face_2___eye_closed_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout imbie_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(5, imbie_000_displaylist_mesh_mat_override_face_2___eye_closed_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout imbie_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt7[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(5, imbie_000_displaylist_mesh_mat_override_face_7___eye_X_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout imbie_002_switch_opt0_001_switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(5, 0, 0, 0, imbie_000_offset_mesh),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(5, imbie_000_offset_001_skinned),
				GEO_ASM(0, geo_move_mario_part_from_parent),
				GEO_ASM(0, geo_mario_tilt_torso),
				GEO_ROTATION_NODE(0, 0, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(5, 68, 0, 0, imbie_000_offset_001_mesh),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(1, 87, 0, 0, NULL),
						GEO_OPEN_NODE(),
							GEO_ASM(0, geo_mario_head_rotation),
							GEO_ROTATION_NODE(0, 0, 0, 0),
							GEO_OPEN_NODE(),
								GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
								GEO_OPEN_NODE(),
									GEO_NODE_START(),
									GEO_OPEN_NODE(),
										GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(5, imbie_000_displaylist_mesh),
											GEO_CLOSE_NODE(),
											GEO_BRANCH(1, imbie_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt1),
											GEO_BRANCH(1, imbie_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt2),
											GEO_BRANCH(1, imbie_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt3),
											GEO_BRANCH(1, imbie_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt4),
											GEO_BRANCH(1, imbie_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt5),
											GEO_BRANCH(1, imbie_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt6),
											GEO_BRANCH(1, imbie_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt7),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
									GEO_BRANCH(1, imbie_002_switch_opt0_001_switch_opt1_jump_imbie_armature_002_switch_option_002),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(0, 142, -51, -126, 15, -33, -133),
								GEO_OPEN_NODE(),
									GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
									GEO_ROTATION_NODE(0, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(5, imbie_000_displaylist_001_mesh),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(0, 142, -51, 126, -15, 33, -133),
								GEO_OPEN_NODE(),
									GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
									GEO_ROTATION_NODE(0, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(5, imbie_000_displaylist_002_mesh),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(1, 67, -10, 79, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(5, 0, 0, 0, imbie_000_offset_003_mesh),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(5, imbie_000_offset_004_skinned),
								GEO_ANIMATED_PART(5, 65, 0, 0, imbie_000_offset_004_mesh),
								GEO_OPEN_NODE(),
									GEO_SWITCH_CASE(1, geo_switch_mario_hand),
									GEO_OPEN_NODE(),
										GEO_NODE_START(),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(1, 60, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_ASM(1, geo_mario_hand_foot_scaler),
												GEO_SCALE(0, 65536),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(5, imbie_000_displaylist_003_mesh),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_BRANCH(1, imbie_002_switch_opt0_001_switch_opt1_jump_imbie_right_hand_open_armature),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(1, 68, -10, -79, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(5, 0, 0, 0, imbie_000_offset_006_mesh),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(5, imbie_000_offset_007_skinned),
								GEO_ANIMATED_PART(5, 65, 0, 0, imbie_000_offset_007_mesh),
								GEO_OPEN_NODE(),
									GEO_SWITCH_CASE(0, geo_switch_mario_hand),
									GEO_OPEN_NODE(),
										GEO_NODE_START(),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(1, 60, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_ASM(0, geo_mario_hand_foot_scaler),
												GEO_SCALE(0, 65536),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(5, imbie_000_displaylist_004_mesh),
												GEO_CLOSE_NODE(),
												GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_BRANCH(1, imbie_002_switch_opt0_001_switch_opt1_jump_imbie_left_hand_open_armature),
										GEO_BRANCH(1, imbie_002_switch_opt0_001_switch_opt1_jump_imbie_left_hand_peace_armature),
										GEO_BRANCH(1, imbie_002_switch_opt0_001_switch_opt1_jump_imbie_left_hand_cap_armature),
										GEO_BRANCH(1, imbie_002_switch_opt0_001_switch_opt1_jump_imbie_left_hand_wing_cap_armature),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(1, 13, -8, 42, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(5, 0, 0, 0, imbie_000_offset_009_mesh),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(5, imbie_000_offset_010_skinned),
						GEO_ANIMATED_PART(5, 89, 0, 0, imbie_000_offset_010_mesh),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(5, 67, 0, 0, imbie_000_offset_011_mesh),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(1, 13, -8, -42, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(5, 0, 0, 0, imbie_000_offset_012_mesh),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(5, imbie_000_offset_013_skinned),
						GEO_ANIMATED_PART(5, 89, 0, 0, imbie_000_offset_013_mesh),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(1, 67, 0, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_ASM(2, geo_mario_hand_foot_scaler),
								GEO_SCALE(0, 65536),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(5, imbie_000_displaylist_005_mesh),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout imbie_002_switch_opt0_001_switch_opt2_jump_imbie_armature_002_switch_option_002[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(1, imbie_002_switch_option_head__no_cap__mesh_mat_override_metal_0),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout imbie_002_switch_opt0_001_switch_opt2_jump_imbie_right_hand_open_armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(1, 60, 0, 0, imbie_002_switch_option_right_hand_open_mesh_mat_override_metal_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout imbie_002_switch_opt0_001_switch_opt2_jump_imbie_left_hand_open_armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(1, 60, 0, 0, imbie_002_switch_option_left_hand_open_mesh_mat_override_metal_0),
		GEO_OPEN_NODE(),
			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout imbie_002_switch_opt0_001_switch_opt2_jump_imbie_left_hand_peace_armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(1, 60, 0, 0, imbie_004_switch_option_left_hand_peace_mesh_mat_override_metal_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout imbie_002_switch_opt0_001_switch_opt2_jump_imbie_left_hand_cap_armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(1, 60, 0, 0, imbie_005_switch_option_left_hand_cap_mesh_mat_override_metal_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout imbie_002_switch_opt0_001_switch_opt2_jump_imbie_left_hand_wing_cap_armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(1, 60, 0, 0, imbie_006_switch_option_left_hand_wing_cap_mesh_mat_override_metal_0),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(4, imbie_006_switch_option_left_hand_wing_cap_wings_mesh_mat_override_metal_0),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout imbie_002_switch_opt0_001_switch_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(1, 0, 0, 0, imbie_000_offset_mesh_mat_override_metal_0),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(1, imbie_000_offset_001_skinned_mat_override_metal_0),
				GEO_ASM(0, geo_move_mario_part_from_parent),
				GEO_ASM(0, geo_mario_tilt_torso),
				GEO_ROTATION_NODE(0, 0, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(1, 68, 0, 0, imbie_000_offset_001_mesh_mat_override_metal_0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(1, 87, 0, 0, NULL),
						GEO_OPEN_NODE(),
							GEO_ASM(0, geo_mario_head_rotation),
							GEO_ROTATION_NODE(0, 0, 0, 0),
							GEO_OPEN_NODE(),
								GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
								GEO_OPEN_NODE(),
									GEO_NODE_START(),
									GEO_OPEN_NODE(),
										GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(1, imbie_000_displaylist_mesh_mat_override_metal_0),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
									GEO_BRANCH(1, imbie_002_switch_opt0_001_switch_opt2_jump_imbie_armature_002_switch_option_002),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(0, 142, -51, -126, 15, -33, -133),
								GEO_OPEN_NODE(),
									GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
									GEO_ROTATION_NODE(0, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(4, imbie_000_displaylist_001_mesh_mat_override_metal_0),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(0, 142, -51, 126, -15, 33, -133),
								GEO_OPEN_NODE(),
									GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
									GEO_ROTATION_NODE(0, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(4, imbie_000_displaylist_002_mesh_mat_override_metal_0),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(1, 67, -10, 79, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(1, 0, 0, 0, imbie_000_offset_003_mesh_mat_override_metal_0),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(1, imbie_000_offset_004_skinned_mat_override_metal_0),
								GEO_ANIMATED_PART(1, 65, 0, 0, imbie_000_offset_004_mesh_mat_override_metal_0),
								GEO_OPEN_NODE(),
									GEO_SWITCH_CASE(1, geo_switch_mario_hand),
									GEO_OPEN_NODE(),
										GEO_NODE_START(),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(1, 60, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_ASM(1, geo_mario_hand_foot_scaler),
												GEO_SCALE(0, 65536),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(1, imbie_000_displaylist_003_mesh_mat_override_metal_0),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_BRANCH(1, imbie_002_switch_opt0_001_switch_opt2_jump_imbie_right_hand_open_armature),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(1, 68, -10, -79, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(1, 0, 0, 0, imbie_000_offset_006_mesh_mat_override_metal_0),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(1, imbie_000_offset_007_skinned_mat_override_metal_0),
								GEO_ANIMATED_PART(1, 65, 0, 0, imbie_000_offset_007_mesh_mat_override_metal_0),
								GEO_OPEN_NODE(),
									GEO_SWITCH_CASE(0, geo_switch_mario_hand),
									GEO_OPEN_NODE(),
										GEO_NODE_START(),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(1, 60, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_ASM(0, geo_mario_hand_foot_scaler),
												GEO_SCALE(0, 65536),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(1, imbie_000_displaylist_004_mesh_mat_override_metal_0),
												GEO_CLOSE_NODE(),
												GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_BRANCH(1, imbie_002_switch_opt0_001_switch_opt2_jump_imbie_left_hand_open_armature),
										GEO_BRANCH(1, imbie_002_switch_opt0_001_switch_opt2_jump_imbie_left_hand_peace_armature),
										GEO_BRANCH(1, imbie_002_switch_opt0_001_switch_opt2_jump_imbie_left_hand_cap_armature),
										GEO_BRANCH(1, imbie_002_switch_opt0_001_switch_opt2_jump_imbie_left_hand_wing_cap_armature),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(1, 13, -8, 42, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(1, 0, 0, 0, imbie_000_offset_009_mesh_mat_override_metal_0),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(1, imbie_000_offset_010_skinned_mat_override_metal_0),
						GEO_ANIMATED_PART(1, 89, 0, 0, imbie_000_offset_010_mesh_mat_override_metal_0),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(1, 67, 0, 0, imbie_000_offset_011_mesh_mat_override_metal_0),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(1, 13, -8, -42, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(1, 0, 0, 0, imbie_000_offset_012_mesh_mat_override_metal_0),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(1, imbie_000_offset_013_skinned_mat_override_metal_0),
						GEO_ANIMATED_PART(1, 89, 0, 0, imbie_000_offset_013_mesh_mat_override_metal_0),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(1, 67, 0, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_ASM(2, geo_mario_hand_foot_scaler),
								GEO_SCALE(0, 65536),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(1, imbie_000_displaylist_005_mesh_mat_override_metal_0),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout imbie_002_switch_opt0_001_switch_opt3_jump_imbie_armature_002_switch_option_002[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(5, imbie_002_switch_option_head__no_cap__mesh_mat_override_metal_0),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout imbie_002_switch_opt0_001_switch_opt3_jump_imbie_right_hand_open_armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(5, 60, 0, 0, imbie_002_switch_option_right_hand_open_mesh_mat_override_metal_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout imbie_002_switch_opt0_001_switch_opt3_jump_imbie_left_hand_open_armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(5, 60, 0, 0, imbie_002_switch_option_left_hand_open_mesh_mat_override_metal_0),
		GEO_OPEN_NODE(),
			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout imbie_002_switch_opt0_001_switch_opt3_jump_imbie_left_hand_peace_armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(5, 60, 0, 0, imbie_004_switch_option_left_hand_peace_mesh_mat_override_metal_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout imbie_002_switch_opt0_001_switch_opt3_jump_imbie_left_hand_cap_armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(5, 60, 0, 0, imbie_005_switch_option_left_hand_cap_mesh_mat_override_metal_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout imbie_002_switch_opt0_001_switch_opt3_jump_imbie_left_hand_wing_cap_armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(5, 60, 0, 0, imbie_006_switch_option_left_hand_wing_cap_mesh_mat_override_metal_0),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(5, imbie_006_switch_option_left_hand_wing_cap_wings_mesh_mat_override_metal_0),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout imbie_002_switch_opt0_001_switch_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(5, 0, 0, 0, imbie_000_offset_mesh_mat_override_metal_0),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(5, imbie_000_offset_001_skinned_mat_override_metal_0),
				GEO_ASM(0, geo_move_mario_part_from_parent),
				GEO_ASM(0, geo_mario_tilt_torso),
				GEO_ROTATION_NODE(0, 0, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(5, 68, 0, 0, imbie_000_offset_001_mesh_mat_override_metal_0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(1, 87, 0, 0, NULL),
						GEO_OPEN_NODE(),
							GEO_ASM(0, geo_mario_head_rotation),
							GEO_ROTATION_NODE(0, 0, 0, 0),
							GEO_OPEN_NODE(),
								GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
								GEO_OPEN_NODE(),
									GEO_NODE_START(),
									GEO_OPEN_NODE(),
										GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(5, imbie_000_displaylist_mesh_mat_override_metal_0),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
									GEO_BRANCH(1, imbie_002_switch_opt0_001_switch_opt3_jump_imbie_armature_002_switch_option_002),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(0, 142, -51, -126, 15, -33, -133),
								GEO_OPEN_NODE(),
									GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
									GEO_ROTATION_NODE(0, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(5, imbie_000_displaylist_001_mesh_mat_override_metal_0),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(0, 142, -51, 126, -15, 33, -133),
								GEO_OPEN_NODE(),
									GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
									GEO_ROTATION_NODE(0, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(5, imbie_000_displaylist_002_mesh_mat_override_metal_0),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(1, 67, -10, 79, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(5, 0, 0, 0, imbie_000_offset_003_mesh_mat_override_metal_0),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(5, imbie_000_offset_004_skinned_mat_override_metal_0),
								GEO_ANIMATED_PART(5, 65, 0, 0, imbie_000_offset_004_mesh_mat_override_metal_0),
								GEO_OPEN_NODE(),
									GEO_SWITCH_CASE(1, geo_switch_mario_hand),
									GEO_OPEN_NODE(),
										GEO_NODE_START(),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(1, 60, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_ASM(1, geo_mario_hand_foot_scaler),
												GEO_SCALE(0, 65536),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(5, imbie_000_displaylist_003_mesh_mat_override_metal_0),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_BRANCH(1, imbie_002_switch_opt0_001_switch_opt3_jump_imbie_right_hand_open_armature),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(1, 68, -10, -79, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(5, 0, 0, 0, imbie_000_offset_006_mesh_mat_override_metal_0),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(5, imbie_000_offset_007_skinned_mat_override_metal_0),
								GEO_ANIMATED_PART(5, 65, 0, 0, imbie_000_offset_007_mesh_mat_override_metal_0),
								GEO_OPEN_NODE(),
									GEO_SWITCH_CASE(0, geo_switch_mario_hand),
									GEO_OPEN_NODE(),
										GEO_NODE_START(),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(1, 60, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_ASM(0, geo_mario_hand_foot_scaler),
												GEO_SCALE(0, 65536),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(5, imbie_000_displaylist_004_mesh_mat_override_metal_0),
												GEO_CLOSE_NODE(),
												GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_BRANCH(1, imbie_002_switch_opt0_001_switch_opt3_jump_imbie_left_hand_open_armature),
										GEO_BRANCH(1, imbie_002_switch_opt0_001_switch_opt3_jump_imbie_left_hand_peace_armature),
										GEO_BRANCH(1, imbie_002_switch_opt0_001_switch_opt3_jump_imbie_left_hand_cap_armature),
										GEO_BRANCH(1, imbie_002_switch_opt0_001_switch_opt3_jump_imbie_left_hand_wing_cap_armature),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(1, 13, -8, 42, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(5, 0, 0, 0, imbie_000_offset_009_mesh_mat_override_metal_0),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(5, imbie_000_offset_010_skinned_mat_override_metal_0),
						GEO_ANIMATED_PART(5, 89, 0, 0, imbie_000_offset_010_mesh_mat_override_metal_0),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(5, 67, 0, 0, imbie_000_offset_011_mesh_mat_override_metal_0),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(1, 13, -8, -42, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(5, 0, 0, 0, imbie_000_offset_012_mesh_mat_override_metal_0),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(5, imbie_000_offset_013_skinned_mat_override_metal_0),
						GEO_ANIMATED_PART(5, 89, 0, 0, imbie_000_offset_013_mesh_mat_override_metal_0),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(1, 67, 0, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_ASM(2, geo_mario_hand_foot_scaler),
								GEO_SCALE(0, 65536),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(5, imbie_000_displaylist_005_mesh_mat_override_metal_0),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout imbie_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(1, imbie_000_displaylist_mesh_mat_override_face_1___eye_half_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout imbie_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(1, imbie_000_displaylist_mesh_mat_override_face_2___eye_closed_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout imbie_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(1, imbie_000_displaylist_mesh_mat_override_face_2___eye_closed_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout imbie_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(1, imbie_000_displaylist_mesh_mat_override_face_2___eye_closed_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout imbie_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(1, imbie_000_displaylist_mesh_mat_override_face_2___eye_closed_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout imbie_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(1, imbie_000_displaylist_mesh_mat_override_face_2___eye_closed_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout imbie_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt7[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(1, imbie_000_displaylist_mesh_mat_override_face_7___eye_X_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout imbie_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SHADOW(1, 180, 100),
		GEO_OPEN_NODE(),
			GEO_SCALE(0, 16384),
			GEO_OPEN_NODE(),
				GEO_ASM(0, geo_mirror_mario_backface_culling),
				GEO_ASM(0, geo_mirror_mario_set_alpha),
				GEO_SWITCH_CASE(0, geo_switch_mario_stand_run),
				GEO_OPEN_NODE(),
					GEO_NODE_START(),
					GEO_OPEN_NODE(),
						GEO_SWITCH_CASE(0, geo_switch_mario_cap_effect),
						GEO_OPEN_NODE(),
							GEO_NODE_START(),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(1, 0, 0, 0, imbie_000_offset_mesh),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(1, imbie_000_offset_001_skinned),
										GEO_ASM(0, geo_move_mario_part_from_parent),
										GEO_ASM(0, geo_mario_tilt_torso),
										GEO_ROTATION_NODE(0, 0, 0, 0),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(1, 68, 0, 0, imbie_000_offset_001_mesh),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(1, 87, 0, 0, NULL),
												GEO_OPEN_NODE(),
													GEO_ASM(0, geo_mario_head_rotation),
													GEO_ROTATION_NODE(0, 0, 0, 0),
													GEO_OPEN_NODE(),
														GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
														GEO_OPEN_NODE(),
															GEO_NODE_START(),
															GEO_OPEN_NODE(),
																GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
																GEO_OPEN_NODE(),
																	GEO_NODE_START(),
																	GEO_OPEN_NODE(),
																		GEO_DISPLAY_LIST(1, imbie_000_displaylist_mesh),
																	GEO_CLOSE_NODE(),
																	GEO_BRANCH(1, imbie_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt1),
																	GEO_BRANCH(1, imbie_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt2),
																	GEO_BRANCH(1, imbie_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt3),
																	GEO_BRANCH(1, imbie_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt4),
																	GEO_BRANCH(1, imbie_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt5),
																	GEO_BRANCH(1, imbie_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt6),
																	GEO_BRANCH(1, imbie_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt7),
																GEO_CLOSE_NODE(),
															GEO_CLOSE_NODE(),
															GEO_BRANCH(1, imbie_armature_002_switch_option_002),
														GEO_CLOSE_NODE(),
														GEO_TRANSLATE_ROTATE(0, 142, -51, -126, 15, -33, -133),
														GEO_OPEN_NODE(),
															GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
															GEO_ROTATION_NODE(0, 0, 0, 0),
															GEO_OPEN_NODE(),
																GEO_DISPLAY_LIST(4, imbie_000_displaylist_001_mesh),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
														GEO_TRANSLATE_ROTATE(0, 142, -51, 126, -15, 33, -133),
														GEO_OPEN_NODE(),
															GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
															GEO_ROTATION_NODE(0, 0, 0, 0),
															GEO_OPEN_NODE(),
																GEO_DISPLAY_LIST(4, imbie_000_displaylist_002_mesh),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
												GEO_ANIMATED_PART(1, 67, -10, 79, NULL),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(1, 0, 0, 0, imbie_000_offset_003_mesh),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(1, imbie_000_offset_004_skinned),
														GEO_ANIMATED_PART(1, 65, 0, 0, imbie_000_offset_004_mesh),
														GEO_OPEN_NODE(),
															GEO_SWITCH_CASE(1, geo_switch_mario_hand),
															GEO_OPEN_NODE(),
																GEO_NODE_START(),
																GEO_OPEN_NODE(),
																	GEO_ANIMATED_PART(1, 60, 0, 0, NULL),
																	GEO_OPEN_NODE(),
																		GEO_ASM(1, geo_mario_hand_foot_scaler),
																		GEO_SCALE(0, 65536),
																		GEO_OPEN_NODE(),
																			GEO_DISPLAY_LIST(1, imbie_000_displaylist_003_mesh),
																		GEO_CLOSE_NODE(),
																	GEO_CLOSE_NODE(),
																GEO_CLOSE_NODE(),
																GEO_BRANCH(1, imbie_right_hand_open_armature),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
												GEO_ANIMATED_PART(1, 68, -10, -79, NULL),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(1, 0, 0, 0, imbie_000_offset_006_mesh),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(1, imbie_000_offset_007_skinned),
														GEO_ANIMATED_PART(1, 65, 0, 0, imbie_000_offset_007_mesh),
														GEO_OPEN_NODE(),
															GEO_SWITCH_CASE(0, geo_switch_mario_hand),
															GEO_OPEN_NODE(),
																GEO_NODE_START(),
																GEO_OPEN_NODE(),
																	GEO_ANIMATED_PART(1, 60, 0, 0, NULL),
																	GEO_OPEN_NODE(),
																		GEO_ASM(0, geo_mario_hand_foot_scaler),
																		GEO_SCALE(0, 65536),
																		GEO_OPEN_NODE(),
																			GEO_DISPLAY_LIST(1, imbie_000_displaylist_004_mesh),
																		GEO_CLOSE_NODE(),
																		GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
																	GEO_CLOSE_NODE(),
																GEO_CLOSE_NODE(),
																GEO_BRANCH(1, imbie_left_hand_open_armature),
																GEO_BRANCH(1, imbie_left_hand_peace_armature),
																GEO_BRANCH(1, imbie_left_hand_cap_armature),
																GEO_BRANCH(1, imbie_left_hand_wing_cap_armature),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_ANIMATED_PART(1, 13, -8, 42, NULL),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(1, 0, 0, 0, imbie_000_offset_009_mesh),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(1, imbie_000_offset_010_skinned),
												GEO_ANIMATED_PART(1, 89, 0, 0, imbie_000_offset_010_mesh),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(1, 67, 0, 0, imbie_000_offset_011_mesh),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_ANIMATED_PART(1, 13, -8, -42, NULL),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(1, 0, 0, 0, imbie_000_offset_012_mesh),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(1, imbie_000_offset_013_skinned),
												GEO_ANIMATED_PART(1, 89, 0, 0, imbie_000_offset_013_mesh),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(1, 67, 0, 0, NULL),
													GEO_OPEN_NODE(),
														GEO_ASM(2, geo_mario_hand_foot_scaler),
														GEO_SCALE(0, 65536),
														GEO_OPEN_NODE(),
															GEO_DISPLAY_LIST(1, imbie_000_displaylist_005_mesh),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_BRANCH(1, imbie_002_switch_opt0_001_switch_opt1),
							GEO_BRANCH(1, imbie_002_switch_opt0_001_switch_opt2),
							GEO_BRANCH(1, imbie_002_switch_opt0_001_switch_opt3),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ASM(1, geo_mirror_mario_backface_culling),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(0, imbie_material_revert_render_settings),
		GEO_DISPLAY_LIST(1, imbie_material_revert_render_settings),
		GEO_DISPLAY_LIST(2, imbie_material_revert_render_settings),
		GEO_DISPLAY_LIST(3, imbie_material_revert_render_settings),
		GEO_DISPLAY_LIST(4, imbie_material_revert_render_settings),
		GEO_DISPLAY_LIST(5, imbie_material_revert_render_settings),
		GEO_DISPLAY_LIST(6, imbie_material_revert_render_settings),
		GEO_DISPLAY_LIST(7, imbie_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
