const GeoLayout peach_2_002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(1, peach_2_002_switch_option_head__no_cap__mesh_mat_override_Face_003_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_2_002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(1, peach_2_002_switch_option_head__no_cap__mesh_mat_override_Face_003_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_2_002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(1, peach_2_002_switch_option_head__no_cap__mesh_mat_override_Face_003_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_2_002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(1, peach_2_002_switch_option_head__no_cap__mesh_mat_override_Face_003_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_2_002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(1, peach_2_002_switch_option_head__no_cap__mesh_mat_override_Face_003_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_2_002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(1, peach_2_002_switch_option_head__no_cap__mesh_mat_override_Face_003_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_2_002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt7[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(1, peach_2_002_switch_option_head__no_cap__mesh_mat_override_Face_003_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_2_armature_002_switch_option_002[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(1, peach_2_002_switch_option_head__no_cap__mesh),
			GEO_CLOSE_NODE(),
			GEO_BRANCH(1, peach_2_002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt1),
			GEO_BRANCH(1, peach_2_002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt2),
			GEO_BRANCH(1, peach_2_002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt3),
			GEO_BRANCH(1, peach_2_002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt4),
			GEO_BRANCH(1, peach_2_002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt5),
			GEO_BRANCH(1, peach_2_002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt6),
			GEO_BRANCH(1, peach_2_002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt7),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_2_right_hand_open_armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(1, 60, 0, 0, peach_2_002_switch_option_right_hand_open_mesh),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_2_left_hand_open_armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(1, 60, 0, 0, peach_2_002_switch_option_left_hand_open_mesh),
		GEO_OPEN_NODE(),
			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_2_left_hand_peace_armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(1, 60, 0, 0, peach_2_004_switch_option_left_hand_peace_mesh),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_2_left_hand_cap_armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(1, 60, 0, 0, peach_2_005_switch_option_left_hand_cap_mesh),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_2_left_hand_wing_cap_armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(1, 60, 0, 0, peach_2_006_switch_option_left_hand_wing_cap_mesh),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(4, peach_2_006_switch_option_left_hand_wing_cap_wings_mesh),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_2_002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(5, peach_2_002_switch_option_head__no_cap__mesh_mat_override_Face_003_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_2_002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(5, peach_2_002_switch_option_head__no_cap__mesh_mat_override_Face_003_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_2_002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(5, peach_2_002_switch_option_head__no_cap__mesh_mat_override_Face_003_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_2_002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(5, peach_2_002_switch_option_head__no_cap__mesh_mat_override_Face_003_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_2_002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(5, peach_2_002_switch_option_head__no_cap__mesh_mat_override_Face_003_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_2_002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(5, peach_2_002_switch_option_head__no_cap__mesh_mat_override_Face_003_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_2_002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt7[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(5, peach_2_002_switch_option_head__no_cap__mesh_mat_override_Face_003_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_2_002_switch_opt0_001_switch_opt1_jump_peach_2_armature_002_switch_option_002[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(5, peach_2_002_switch_option_head__no_cap__mesh),
			GEO_CLOSE_NODE(),
			GEO_BRANCH(1, peach_2_002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt1),
			GEO_BRANCH(1, peach_2_002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt2),
			GEO_BRANCH(1, peach_2_002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt3),
			GEO_BRANCH(1, peach_2_002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt4),
			GEO_BRANCH(1, peach_2_002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt5),
			GEO_BRANCH(1, peach_2_002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt6),
			GEO_BRANCH(1, peach_2_002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt7),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_2_002_switch_opt0_001_switch_opt1_jump_peach_2_right_hand_open_armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(5, 60, 0, 0, peach_2_002_switch_option_right_hand_open_mesh),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_2_002_switch_opt0_001_switch_opt1_jump_peach_2_left_hand_open_armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(5, 60, 0, 0, peach_2_002_switch_option_left_hand_open_mesh),
		GEO_OPEN_NODE(),
			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_2_002_switch_opt0_001_switch_opt1_jump_peach_2_left_hand_peace_armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(5, 60, 0, 0, peach_2_004_switch_option_left_hand_peace_mesh),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_2_002_switch_opt0_001_switch_opt1_jump_peach_2_left_hand_cap_armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(5, 60, 0, 0, peach_2_005_switch_option_left_hand_cap_mesh),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_2_002_switch_opt0_001_switch_opt1_jump_peach_2_left_hand_wing_cap_armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(5, 60, 0, 0, peach_2_006_switch_option_left_hand_wing_cap_mesh),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(5, peach_2_006_switch_option_left_hand_wing_cap_wings_mesh),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_2_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(5, peach_2_000_displaylist_mesh_mat_override_Face_003_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_2_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(5, peach_2_000_displaylist_mesh_mat_override_Face_003_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_2_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(5, peach_2_000_displaylist_mesh_mat_override_Face_003_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_2_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(5, peach_2_000_displaylist_mesh_mat_override_Face_003_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_2_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(5, peach_2_000_displaylist_mesh_mat_override_Face_003_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_2_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(5, peach_2_000_displaylist_mesh_mat_override_face_0___eye_open_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_2_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt7[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(5, peach_2_000_displaylist_mesh_mat_override_Face_003_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_2_002_switch_opt0_001_switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(1, 14, 172, 199, NULL),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(5, 177, 0, -1, peach_2_000_offset_mesh),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(5, peach_2_000_offset_001_skinned),
				GEO_ASM(0, geo_move_mario_part_from_parent),
				GEO_ASM(0, geo_mario_tilt_torso),
				GEO_ROTATION_NODE(0, 0, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(5, 122, -5, 2, peach_2_000_offset_001_mesh),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(1, 63, 3, 1, NULL),
						GEO_OPEN_NODE(),
							GEO_ASM(0, geo_mario_head_rotation),
							GEO_ROTATION_NODE(0, 0, 0, 0),
							GEO_OPEN_NODE(),
								GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
								GEO_OPEN_NODE(),
									GEO_NODE_START(),
									GEO_OPEN_NODE(),
										GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(5, peach_2_000_displaylist_mesh),
											GEO_CLOSE_NODE(),
											GEO_BRANCH(1, peach_2_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt1),
											GEO_BRANCH(1, peach_2_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt2),
											GEO_BRANCH(1, peach_2_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt3),
											GEO_BRANCH(1, peach_2_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt4),
											GEO_BRANCH(1, peach_2_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt5),
											GEO_BRANCH(1, peach_2_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt6),
											GEO_BRANCH(1, peach_2_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt7),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
									GEO_BRANCH(1, peach_2_002_switch_opt0_001_switch_opt1_jump_peach_2_armature_002_switch_option_002),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(0, -165, -92, -68, 15, -33, -133),
								GEO_OPEN_NODE(),
									GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
									GEO_ROTATION_NODE(0, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(5, peach_2_000_displaylist_001_mesh),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(0, -163, -93, 59, -15, 33, -133),
								GEO_OPEN_NODE(),
									GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
									GEO_ROTATION_NODE(0, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(5, peach_2_000_displaylist_002_mesh),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_TRANSLATE_ROTATE(1, -4, -28, 46, -1, 0, -1),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_TRANSLATE_ROTATE(1, 0, 0, 0, -1, -2, -2),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(5, 0, 0, 0, peach_2_000_offset_003_mesh),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(5, peach_2_000_offset_004_skinned),
										GEO_ANIMATED_PART(5, 124, -51, 11, peach_2_000_offset_004_mesh),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(5, peach_2_000_displaylist_003_skinned),
											GEO_SWITCH_CASE(1, geo_switch_mario_hand),
											GEO_OPEN_NODE(),
												GEO_NODE_START(),
												GEO_OPEN_NODE(),
													GEO_TRANSLATE_ROTATE(1, 83, 1, 9, 0, 1, 3),
													GEO_OPEN_NODE(),
														GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
														GEO_OPEN_NODE(),
															GEO_ASM(1, geo_mario_hand_foot_scaler),
															GEO_SCALE(0, 65536),
															GEO_OPEN_NODE(),
																GEO_DISPLAY_LIST(5, peach_2_000_displaylist_003_mesh),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
												GEO_BRANCH(1, peach_2_002_switch_opt0_001_switch_opt1_jump_peach_2_right_hand_open_armature),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_TRANSLATE_ROTATE(1, 3, -25, -67, 4, 5, 0),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_TRANSLATE_ROTATE(1, 0, 0, 0, -3, -5, 2),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(5, 0, 0, 0, peach_2_000_offset_006_mesh),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(5, peach_2_000_offset_007_skinned),
										GEO_ANIMATED_PART(5, 134, -35, 0, peach_2_000_offset_007_mesh),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(5, peach_2_000_displaylist_004_skinned),
											GEO_SWITCH_CASE(0, geo_switch_mario_hand),
											GEO_OPEN_NODE(),
												GEO_NODE_START(),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(1, 94, -11, -5, NULL),
													GEO_OPEN_NODE(),
														GEO_ASM(0, geo_mario_hand_foot_scaler),
														GEO_SCALE(0, 65536),
														GEO_OPEN_NODE(),
															GEO_DISPLAY_LIST(5, peach_2_000_displaylist_004_mesh),
														GEO_CLOSE_NODE(),
														GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
												GEO_BRANCH(1, peach_2_002_switch_opt0_001_switch_opt1_jump_peach_2_left_hand_open_armature),
												GEO_BRANCH(1, peach_2_002_switch_opt0_001_switch_opt1_jump_peach_2_left_hand_peace_armature),
												GEO_BRANCH(1, peach_2_002_switch_opt0_001_switch_opt1_jump_peach_2_left_hand_cap_armature),
												GEO_BRANCH(1, peach_2_002_switch_opt0_001_switch_opt1_jump_peach_2_left_hand_wing_cap_armature),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(1, -155, 13, 64, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(5, 79, 0, 0, peach_2_000_offset_010_mesh),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(5, 103, 77, -18, peach_2_000_offset_011_mesh),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(1, -153, 15, -60, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(5, 79, 0, 0, peach_2_000_offset_013_mesh),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(1, 101, 75, 19, NULL),
							GEO_OPEN_NODE(),
								GEO_ASM(2, geo_mario_hand_foot_scaler),
								GEO_SCALE(0, 65536),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(5, peach_2_000_displaylist_005_mesh),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_2_002_switch_opt0_001_switch_opt2_jump_peach_2_armature_002_switch_option_002[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(1, peach_2_002_switch_option_head__no_cap__mesh_mat_override_metal_0),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_2_002_switch_opt0_001_switch_opt2_jump_peach_2_right_hand_open_armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(1, 60, 0, 0, peach_2_002_switch_option_right_hand_open_mesh_mat_override_metal_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_2_002_switch_opt0_001_switch_opt2_jump_peach_2_left_hand_open_armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(1, 60, 0, 0, peach_2_002_switch_option_left_hand_open_mesh_mat_override_metal_0),
		GEO_OPEN_NODE(),
			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_2_002_switch_opt0_001_switch_opt2_jump_peach_2_left_hand_peace_armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(1, 60, 0, 0, peach_2_004_switch_option_left_hand_peace_mesh_mat_override_metal_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_2_002_switch_opt0_001_switch_opt2_jump_peach_2_left_hand_cap_armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(1, 60, 0, 0, peach_2_005_switch_option_left_hand_cap_mesh_mat_override_metal_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_2_002_switch_opt0_001_switch_opt2_jump_peach_2_left_hand_wing_cap_armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(1, 60, 0, 0, peach_2_006_switch_option_left_hand_wing_cap_mesh_mat_override_metal_0),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(4, peach_2_006_switch_option_left_hand_wing_cap_wings_mesh_mat_override_metal_0),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_2_002_switch_opt0_001_switch_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(1, 14, 172, 199, NULL),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(1, 177, 0, -1, peach_2_000_offset_mesh_mat_override_metal_0),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(1, peach_2_000_offset_001_skinned_mat_override_metal_0),
				GEO_ASM(0, geo_move_mario_part_from_parent),
				GEO_ASM(0, geo_mario_tilt_torso),
				GEO_ROTATION_NODE(0, 0, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(1, 122, -5, 2, peach_2_000_offset_001_mesh_mat_override_metal_0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(1, 63, 3, 1, NULL),
						GEO_OPEN_NODE(),
							GEO_ASM(0, geo_mario_head_rotation),
							GEO_ROTATION_NODE(0, 0, 0, 0),
							GEO_OPEN_NODE(),
								GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
								GEO_OPEN_NODE(),
									GEO_NODE_START(),
									GEO_OPEN_NODE(),
										GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(1, peach_2_000_displaylist_mesh_mat_override_metal_0),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
									GEO_BRANCH(1, peach_2_002_switch_opt0_001_switch_opt2_jump_peach_2_armature_002_switch_option_002),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(0, -165, -92, -68, 15, -33, -133),
								GEO_OPEN_NODE(),
									GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
									GEO_ROTATION_NODE(0, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(4, peach_2_000_displaylist_001_mesh_mat_override_metal_0),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(0, -163, -93, 59, -15, 33, -133),
								GEO_OPEN_NODE(),
									GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
									GEO_ROTATION_NODE(0, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(4, peach_2_000_displaylist_002_mesh_mat_override_metal_0),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_TRANSLATE_ROTATE(1, -4, -28, 46, -1, 0, -1),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_TRANSLATE_ROTATE(1, 0, 0, 0, -1, -2, -2),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(1, 0, 0, 0, peach_2_000_offset_003_mesh_mat_override_metal_0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(1, peach_2_000_offset_004_skinned_mat_override_metal_0),
										GEO_ANIMATED_PART(1, 124, -51, 11, peach_2_000_offset_004_mesh_mat_override_metal_0),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(1, peach_2_000_displaylist_003_skinned_mat_override_metal_0),
											GEO_SWITCH_CASE(1, geo_switch_mario_hand),
											GEO_OPEN_NODE(),
												GEO_NODE_START(),
												GEO_OPEN_NODE(),
													GEO_TRANSLATE_ROTATE(1, 83, 1, 9, 0, 1, 3),
													GEO_OPEN_NODE(),
														GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
														GEO_OPEN_NODE(),
															GEO_ASM(1, geo_mario_hand_foot_scaler),
															GEO_SCALE(0, 65536),
															GEO_OPEN_NODE(),
																GEO_DISPLAY_LIST(1, peach_2_000_displaylist_003_mesh_mat_override_metal_0),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
												GEO_BRANCH(1, peach_2_002_switch_opt0_001_switch_opt2_jump_peach_2_right_hand_open_armature),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_TRANSLATE_ROTATE(1, 3, -25, -67, 4, 5, 0),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_TRANSLATE_ROTATE(1, 0, 0, 0, -3, -5, 2),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(1, 0, 0, 0, peach_2_000_offset_006_mesh_mat_override_metal_0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(1, peach_2_000_offset_007_skinned_mat_override_metal_0),
										GEO_ANIMATED_PART(1, 134, -35, 0, peach_2_000_offset_007_mesh_mat_override_metal_0),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(1, peach_2_000_displaylist_004_skinned_mat_override_metal_0),
											GEO_SWITCH_CASE(0, geo_switch_mario_hand),
											GEO_OPEN_NODE(),
												GEO_NODE_START(),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(1, 94, -11, -5, NULL),
													GEO_OPEN_NODE(),
														GEO_ASM(0, geo_mario_hand_foot_scaler),
														GEO_SCALE(0, 65536),
														GEO_OPEN_NODE(),
															GEO_DISPLAY_LIST(1, peach_2_000_displaylist_004_mesh_mat_override_metal_0),
														GEO_CLOSE_NODE(),
														GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
												GEO_BRANCH(1, peach_2_002_switch_opt0_001_switch_opt2_jump_peach_2_left_hand_open_armature),
												GEO_BRANCH(1, peach_2_002_switch_opt0_001_switch_opt2_jump_peach_2_left_hand_peace_armature),
												GEO_BRANCH(1, peach_2_002_switch_opt0_001_switch_opt2_jump_peach_2_left_hand_cap_armature),
												GEO_BRANCH(1, peach_2_002_switch_opt0_001_switch_opt2_jump_peach_2_left_hand_wing_cap_armature),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(1, -155, 13, 64, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(1, 79, 0, 0, peach_2_000_offset_010_mesh_mat_override_metal_0),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(1, 103, 77, -18, peach_2_000_offset_011_mesh_mat_override_metal_0),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(1, -153, 15, -60, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(1, 79, 0, 0, peach_2_000_offset_013_mesh_mat_override_metal_0),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(1, 101, 75, 19, NULL),
							GEO_OPEN_NODE(),
								GEO_ASM(2, geo_mario_hand_foot_scaler),
								GEO_SCALE(0, 65536),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(1, peach_2_000_displaylist_005_mesh_mat_override_metal_0),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_2_002_switch_opt0_001_switch_opt3_jump_peach_2_armature_002_switch_option_002[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(5, peach_2_002_switch_option_head__no_cap__mesh_mat_override_metal_0),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_2_002_switch_opt0_001_switch_opt3_jump_peach_2_right_hand_open_armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(5, 60, 0, 0, peach_2_002_switch_option_right_hand_open_mesh_mat_override_metal_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_2_002_switch_opt0_001_switch_opt3_jump_peach_2_left_hand_open_armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(5, 60, 0, 0, peach_2_002_switch_option_left_hand_open_mesh_mat_override_metal_0),
		GEO_OPEN_NODE(),
			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_2_002_switch_opt0_001_switch_opt3_jump_peach_2_left_hand_peace_armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(5, 60, 0, 0, peach_2_004_switch_option_left_hand_peace_mesh_mat_override_metal_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_2_002_switch_opt0_001_switch_opt3_jump_peach_2_left_hand_cap_armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(5, 60, 0, 0, peach_2_005_switch_option_left_hand_cap_mesh_mat_override_metal_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_2_002_switch_opt0_001_switch_opt3_jump_peach_2_left_hand_wing_cap_armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(5, 60, 0, 0, peach_2_006_switch_option_left_hand_wing_cap_mesh_mat_override_metal_0),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(5, peach_2_006_switch_option_left_hand_wing_cap_wings_mesh_mat_override_metal_0),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_2_002_switch_opt0_001_switch_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(1, 14, 172, 199, NULL),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(5, 177, 0, -1, peach_2_000_offset_mesh_mat_override_metal_0),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(5, peach_2_000_offset_001_skinned_mat_override_metal_0),
				GEO_ASM(0, geo_move_mario_part_from_parent),
				GEO_ASM(0, geo_mario_tilt_torso),
				GEO_ROTATION_NODE(0, 0, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(5, 122, -5, 2, peach_2_000_offset_001_mesh_mat_override_metal_0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(1, 63, 3, 1, NULL),
						GEO_OPEN_NODE(),
							GEO_ASM(0, geo_mario_head_rotation),
							GEO_ROTATION_NODE(0, 0, 0, 0),
							GEO_OPEN_NODE(),
								GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
								GEO_OPEN_NODE(),
									GEO_NODE_START(),
									GEO_OPEN_NODE(),
										GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(5, peach_2_000_displaylist_mesh_mat_override_metal_0),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
									GEO_BRANCH(1, peach_2_002_switch_opt0_001_switch_opt3_jump_peach_2_armature_002_switch_option_002),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(0, -165, -92, -68, 15, -33, -133),
								GEO_OPEN_NODE(),
									GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
									GEO_ROTATION_NODE(0, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(5, peach_2_000_displaylist_001_mesh_mat_override_metal_0),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(0, -163, -93, 59, -15, 33, -133),
								GEO_OPEN_NODE(),
									GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
									GEO_ROTATION_NODE(0, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(5, peach_2_000_displaylist_002_mesh_mat_override_metal_0),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_TRANSLATE_ROTATE(1, -4, -28, 46, -1, 0, -1),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_TRANSLATE_ROTATE(1, 0, 0, 0, -1, -2, -2),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(5, 0, 0, 0, peach_2_000_offset_003_mesh_mat_override_metal_0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(5, peach_2_000_offset_004_skinned_mat_override_metal_0),
										GEO_ANIMATED_PART(5, 124, -51, 11, peach_2_000_offset_004_mesh_mat_override_metal_0),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(5, peach_2_000_displaylist_003_skinned_mat_override_metal_0),
											GEO_SWITCH_CASE(1, geo_switch_mario_hand),
											GEO_OPEN_NODE(),
												GEO_NODE_START(),
												GEO_OPEN_NODE(),
													GEO_TRANSLATE_ROTATE(1, 83, 1, 9, 0, 1, 3),
													GEO_OPEN_NODE(),
														GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
														GEO_OPEN_NODE(),
															GEO_ASM(1, geo_mario_hand_foot_scaler),
															GEO_SCALE(0, 65536),
															GEO_OPEN_NODE(),
																GEO_DISPLAY_LIST(5, peach_2_000_displaylist_003_mesh_mat_override_metal_0),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
												GEO_BRANCH(1, peach_2_002_switch_opt0_001_switch_opt3_jump_peach_2_right_hand_open_armature),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_TRANSLATE_ROTATE(1, 3, -25, -67, 4, 5, 0),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_TRANSLATE_ROTATE(1, 0, 0, 0, -3, -5, 2),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(5, 0, 0, 0, peach_2_000_offset_006_mesh_mat_override_metal_0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(5, peach_2_000_offset_007_skinned_mat_override_metal_0),
										GEO_ANIMATED_PART(5, 134, -35, 0, peach_2_000_offset_007_mesh_mat_override_metal_0),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(5, peach_2_000_displaylist_004_skinned_mat_override_metal_0),
											GEO_SWITCH_CASE(0, geo_switch_mario_hand),
											GEO_OPEN_NODE(),
												GEO_NODE_START(),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(1, 94, -11, -5, NULL),
													GEO_OPEN_NODE(),
														GEO_ASM(0, geo_mario_hand_foot_scaler),
														GEO_SCALE(0, 65536),
														GEO_OPEN_NODE(),
															GEO_DISPLAY_LIST(5, peach_2_000_displaylist_004_mesh_mat_override_metal_0),
														GEO_CLOSE_NODE(),
														GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
												GEO_BRANCH(1, peach_2_002_switch_opt0_001_switch_opt3_jump_peach_2_left_hand_open_armature),
												GEO_BRANCH(1, peach_2_002_switch_opt0_001_switch_opt3_jump_peach_2_left_hand_peace_armature),
												GEO_BRANCH(1, peach_2_002_switch_opt0_001_switch_opt3_jump_peach_2_left_hand_cap_armature),
												GEO_BRANCH(1, peach_2_002_switch_opt0_001_switch_opt3_jump_peach_2_left_hand_wing_cap_armature),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(1, -155, 13, 64, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(5, 79, 0, 0, peach_2_000_offset_010_mesh_mat_override_metal_0),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(5, 103, 77, -18, peach_2_000_offset_011_mesh_mat_override_metal_0),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(1, -153, 15, -60, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(5, 79, 0, 0, peach_2_000_offset_013_mesh_mat_override_metal_0),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(1, 101, 75, 19, NULL),
							GEO_OPEN_NODE(),
								GEO_ASM(2, geo_mario_hand_foot_scaler),
								GEO_SCALE(0, 65536),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(5, peach_2_000_displaylist_005_mesh_mat_override_metal_0),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_2_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(1, peach_2_000_displaylist_mesh_mat_override_Face_003_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_2_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(1, peach_2_000_displaylist_mesh_mat_override_Face_003_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_2_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(1, peach_2_000_displaylist_mesh_mat_override_Face_003_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_2_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(1, peach_2_000_displaylist_mesh_mat_override_Face_003_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_2_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(1, peach_2_000_displaylist_mesh_mat_override_Face_003_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_2_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(1, peach_2_000_displaylist_mesh_mat_override_face_0___eye_open_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_2_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt7[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(1, peach_2_000_displaylist_mesh_mat_override_Face_003_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_2_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SHADOW(1, 180, 100),
		GEO_OPEN_NODE(),
			GEO_SCALE(0, 16384),
			GEO_OPEN_NODE(),
				GEO_ASM(0, geo_mirror_mario_backface_culling),
				GEO_ASM(0, geo_mirror_mario_set_alpha),
				GEO_SWITCH_CASE(0, geo_switch_mario_stand_run),
				GEO_OPEN_NODE(),
					GEO_NODE_START(),
					GEO_OPEN_NODE(),
						GEO_SWITCH_CASE(0, geo_switch_mario_cap_effect),
						GEO_OPEN_NODE(),
							GEO_NODE_START(),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(1, 14, 172, 199, NULL),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(1, 177, 0, -1, peach_2_000_offset_mesh),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(1, peach_2_000_offset_001_skinned),
										GEO_ASM(0, geo_move_mario_part_from_parent),
										GEO_ASM(0, geo_mario_tilt_torso),
										GEO_ROTATION_NODE(0, 0, 0, 0),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(1, 122, -5, 2, peach_2_000_offset_001_mesh),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(1, 63, 3, 1, NULL),
												GEO_OPEN_NODE(),
													GEO_ASM(0, geo_mario_head_rotation),
													GEO_ROTATION_NODE(0, 0, 0, 0),
													GEO_OPEN_NODE(),
														GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
														GEO_OPEN_NODE(),
															GEO_NODE_START(),
															GEO_OPEN_NODE(),
																GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
																GEO_OPEN_NODE(),
																	GEO_NODE_START(),
																	GEO_OPEN_NODE(),
																		GEO_DISPLAY_LIST(1, peach_2_000_displaylist_mesh),
																	GEO_CLOSE_NODE(),
																	GEO_BRANCH(1, peach_2_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt1),
																	GEO_BRANCH(1, peach_2_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt2),
																	GEO_BRANCH(1, peach_2_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt3),
																	GEO_BRANCH(1, peach_2_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt4),
																	GEO_BRANCH(1, peach_2_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt5),
																	GEO_BRANCH(1, peach_2_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt6),
																	GEO_BRANCH(1, peach_2_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt7),
																GEO_CLOSE_NODE(),
															GEO_CLOSE_NODE(),
															GEO_BRANCH(1, peach_2_armature_002_switch_option_002),
														GEO_CLOSE_NODE(),
														GEO_TRANSLATE_ROTATE(0, -165, -92, -68, 15, -33, -133),
														GEO_OPEN_NODE(),
															GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
															GEO_ROTATION_NODE(0, 0, 0, 0),
															GEO_OPEN_NODE(),
																GEO_DISPLAY_LIST(4, peach_2_000_displaylist_001_mesh),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
														GEO_TRANSLATE_ROTATE(0, -163, -93, 59, -15, 33, -133),
														GEO_OPEN_NODE(),
															GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
															GEO_ROTATION_NODE(0, 0, 0, 0),
															GEO_OPEN_NODE(),
																GEO_DISPLAY_LIST(4, peach_2_000_displaylist_002_mesh),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
												GEO_TRANSLATE_ROTATE(1, -4, -28, 46, -1, 0, -1),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
													GEO_OPEN_NODE(),
														GEO_TRANSLATE_ROTATE(1, 0, 0, 0, -1, -2, -2),
														GEO_OPEN_NODE(),
															GEO_ANIMATED_PART(1, 0, 0, 0, peach_2_000_offset_003_mesh),
															GEO_OPEN_NODE(),
																GEO_DISPLAY_LIST(1, peach_2_000_offset_004_skinned),
																GEO_ANIMATED_PART(1, 124, -51, 11, peach_2_000_offset_004_mesh),
																GEO_OPEN_NODE(),
																	GEO_DISPLAY_LIST(1, peach_2_000_displaylist_003_skinned),
																	GEO_SWITCH_CASE(1, geo_switch_mario_hand),
																	GEO_OPEN_NODE(),
																		GEO_NODE_START(),
																		GEO_OPEN_NODE(),
																			GEO_TRANSLATE_ROTATE(1, 83, 1, 9, 0, 1, 3),
																			GEO_OPEN_NODE(),
																				GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
																				GEO_OPEN_NODE(),
																					GEO_ASM(1, geo_mario_hand_foot_scaler),
																					GEO_SCALE(0, 65536),
																					GEO_OPEN_NODE(),
																						GEO_DISPLAY_LIST(1, peach_2_000_displaylist_003_mesh),
																					GEO_CLOSE_NODE(),
																				GEO_CLOSE_NODE(),
																			GEO_CLOSE_NODE(),
																		GEO_CLOSE_NODE(),
																		GEO_BRANCH(1, peach_2_right_hand_open_armature),
																	GEO_CLOSE_NODE(),
																GEO_CLOSE_NODE(),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
												GEO_TRANSLATE_ROTATE(1, 3, -25, -67, 4, 5, 0),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
													GEO_OPEN_NODE(),
														GEO_TRANSLATE_ROTATE(1, 0, 0, 0, -3, -5, 2),
														GEO_OPEN_NODE(),
															GEO_ANIMATED_PART(1, 0, 0, 0, peach_2_000_offset_006_mesh),
															GEO_OPEN_NODE(),
																GEO_DISPLAY_LIST(1, peach_2_000_offset_007_skinned),
																GEO_ANIMATED_PART(1, 134, -35, 0, peach_2_000_offset_007_mesh),
																GEO_OPEN_NODE(),
																	GEO_DISPLAY_LIST(1, peach_2_000_displaylist_004_skinned),
																	GEO_SWITCH_CASE(0, geo_switch_mario_hand),
																	GEO_OPEN_NODE(),
																		GEO_NODE_START(),
																		GEO_OPEN_NODE(),
																			GEO_ANIMATED_PART(1, 94, -11, -5, NULL),
																			GEO_OPEN_NODE(),
																				GEO_ASM(0, geo_mario_hand_foot_scaler),
																				GEO_SCALE(0, 65536),
																				GEO_OPEN_NODE(),
																					GEO_DISPLAY_LIST(1, peach_2_000_displaylist_004_mesh),
																				GEO_CLOSE_NODE(),
																				GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
																			GEO_CLOSE_NODE(),
																		GEO_CLOSE_NODE(),
																		GEO_BRANCH(1, peach_2_left_hand_open_armature),
																		GEO_BRANCH(1, peach_2_left_hand_peace_armature),
																		GEO_BRANCH(1, peach_2_left_hand_cap_armature),
																		GEO_BRANCH(1, peach_2_left_hand_wing_cap_armature),
																	GEO_CLOSE_NODE(),
																GEO_CLOSE_NODE(),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_ANIMATED_PART(1, -155, 13, 64, NULL),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(1, 79, 0, 0, peach_2_000_offset_010_mesh),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(1, 103, 77, -18, peach_2_000_offset_011_mesh),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_ANIMATED_PART(1, -153, 15, -60, NULL),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(1, 79, 0, 0, peach_2_000_offset_013_mesh),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(1, 101, 75, 19, NULL),
													GEO_OPEN_NODE(),
														GEO_ASM(2, geo_mario_hand_foot_scaler),
														GEO_SCALE(0, 65536),
														GEO_OPEN_NODE(),
															GEO_DISPLAY_LIST(1, peach_2_000_displaylist_005_mesh),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_BRANCH(1, peach_2_002_switch_opt0_001_switch_opt1),
							GEO_BRANCH(1, peach_2_002_switch_opt0_001_switch_opt2),
							GEO_BRANCH(1, peach_2_002_switch_opt0_001_switch_opt3),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ASM(1, geo_mirror_mario_backface_culling),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(0, peach_2_material_revert_render_settings),
		GEO_DISPLAY_LIST(1, peach_2_material_revert_render_settings),
		GEO_DISPLAY_LIST(2, peach_2_material_revert_render_settings),
		GEO_DISPLAY_LIST(3, peach_2_material_revert_render_settings),
		GEO_DISPLAY_LIST(4, peach_2_material_revert_render_settings),
		GEO_DISPLAY_LIST(5, peach_2_material_revert_render_settings),
		GEO_DISPLAY_LIST(6, peach_2_material_revert_render_settings),
		GEO_DISPLAY_LIST(7, peach_2_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
